# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: $(majorMinorVersion).$(revision)

variables:
  majorMinorVersion: 0.1
  revision: $[counter(variables['majorMinorVersion'], 0)]

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    displayName: Build
    jobs:
      - job: BuildApplication
        steps:
          - task: NodeTool@0
            displayName: "Use Node 22.x"
            inputs:
              versionSpec: "22.x"
          # - task: Npm@1
          #   displayName: "npm install"
          #   inputs:
          #     command: "install"
          - task: Npm@1
            displayName: "npm version"
            inputs:
              command: "custom"
              customCommand: "version $(Build.BuildNumber) --no-git-tag-version"
          - task: Docker@2
            displayName: 'Docker Build'
            inputs:
              containerRegistry: 'ACR - TravelZoom'
              repository: 'travelzoom-backend'
              command: build
              Dockerfile: Dockerfile
              tags: |
                $(Build.BuildNumber)
              arguments: '--build-arg VERSION=$(Build.BuildNumber)'
              addPipelineData: false
              addBaseImageData: false
          - task: Docker@2
            displayName: 'Docker Push'
            inputs:
              containerRegistry: 'ACR - TravelZoom'
              repository: 'travelzoom-backend'
              command: push
              tags: |
                $(Build.BuildNumber)
              addPipelineData: false
              addBaseImageData: false

  - stage: Deploy_Dev
    displayName: Deploy Dev
    dependsOn: Build
    jobs:
      - deployment: Deploy_App_Dev
        displayName: Deploy App to Dev Environment
        environment:
          name: dev
        strategy:
          runOnce:
            deploy:
              steps:
              - task: AzureWebAppContainer@1
                displayName: 'Azure Web App Container'
                inputs:
                  azureSubscription: 'Directions B.V.(76d9400a-8a77-4679-acb6-2d68e2fb80e9)'
                  appName: 'travelzoom-backend-dev'
                  deployToSlotOrASE: true
                  resourceGroupName: 'travelzoom-resource-group'
                  slotName: 'production'
                  containers: 'travelzoom.azurecr.io/travelzoom-backend:$(Build.BuildNumber)'